// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { anchor } from "./anchor.js";
import { anchorGroup } from "./anchorGroup.js";
import { anchorIndex } from "./anchorIndex.js";
import { clear } from "./clear.js";
import { collapse } from "./collapse.js";
import { create } from "./create.js";
import { focus } from "./focus.js";
import { focusIndex } from "./focusIndex.js";
import { goTo } from "./goTo.js";
import { goToBottom } from "./goToBottom.js";
import { goToIndex } from "./goToIndex.js";
import { goToNext } from "./goToNext.js";
import { goToPrev } from "./goToPrev.js";
import { goToTop } from "./goToTop.js";
import { groups } from "./groups.js";
import { handleKeyboardEvent } from "./handleKeyboardEvent.js";
import { handleMouseEvent } from "./handleMouseEvent.js";
import { hasMultipleSelections } from "./hasMultipleSelections.js";
import { hasNoSelection } from "./hasNoSelection.js";
import { hasSelection } from "./hasSelection.js";
import { isFirstSelection } from "./isFirstSelection.js";
import { isFirstSelectionInGroup } from "./isFirstSelectionInGroup.js";
import { isLastSelection } from "./isLastSelection.js";
import { isLastSelectionInGroup } from "./isLastSelectionInGroup.js";
import { isSelected } from "./isSelected.js";
import { lastSelectedIndex } from "./lastSelectedIndex.js";
import { normalize } from "./normalize.js";
import { select } from "./select.js";
import { selectAll } from "./selectAll.js";
import { selectNext } from "./selectNext.js";
import { selectPrev } from "./selectPrev.js";
import { selectTo } from "./selectTo.js";
import { selectToBottom } from "./selectToBottom.js";
import { selectToTop } from "./selectToTop.js";
import { setSelectables } from "./setSelectables.js";
import { toggleSelect } from "./toggleSelect.js";
import { unselect } from "./unselect.js";

export const LSM = {
    anchor,
    anchorGroup,
    anchorIndex,
    clear,
    collapse,
    create,
    focus,
    focusIndex,
    goTo,
    goToBottom,
    goToIndex,
    goToNext,
    goToPrev,
    goToTop,
    groups,
    handleKeyboardEvent,
    handleMouseEvent,
    hasMultipleSelections,
    hasNoSelection,
    hasSelection,
    isFirstSelection,
    isFirstSelectionInGroup,
    isLastSelection,
    isLastSelectionInGroup,
    isSelected,
    lastSelectedIndex,
    normalize,
    select,
    selectAll,
    selectNext,
    selectPrev,
    selectTo,
    selectToBottom,
    selectToTop,
    setSelectables,
    toggleSelect,
    unselect,
}
